import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'fr' | 'en' | 'es' | 'de' | 'it' | 'pt' | 'ar' | 'zh' | 'ja' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    welcome: "Bienvenue",
    description: "Conçue pour les membres distingués de l'élite mondiale, Aurora Society est une application réservée aux personnalités les plus influentes.",
    continue: "Continue",
    selectLanguage: "Langue",
    register: "S'inscrire",
    signIn: "Se connecter",
    allRightsReserved: "Tous droits réservés",
    termsAndConditions: "Conditions Générales",
    contact: "Contact",
    // Login & Registration pages
    email: "Email",
    invitationCode: "Code d'invitation (obligatoire)",
    login: "Se connecter",
    registration: "INSCRIPTION",
    profilePhoto: "Photo de Profil",
    referralCode: "Code de Parrainage",
    idCard: "Carte d'Identité",
    scanId: "Scanner la Carte d'Identité",
    firstName: "Prénom",
    lastName: "Nom",
    honorificTitle: "Titre Honorifique",
    mobileNumber: "Numéro de Mobile",
    jobFunction: "Fonction/Activité",
    activityDomain: "Domaine d'Activité",
    wealthLevel: "Niveau de Patrimoine",
    personalQuote: "Citation Personnelle (facultatif)",
    photoFormatsHint: "Format JPG, PNG ou GIF recommandé",
    chooseFile: "Choisir un fichier",
    jobFunctionPlaceholder: "CEO, PDG, Directeur...",
    emailPlaceholder: "votre@email.com",
    selectTitle: "Sélectionnez votre titre",
    selectActivityDomain: "Sélectionnez votre domaine",
    personalQuotePlaceholder: "À remplir plus tard...",
    founderMember: "Membre Fondateur",
    associatedAccounts: "Comptes Associés",
    acceptTermsPrefix: "J'accepte les",
    loading: "Chargement...",
    exclusiveCircle: "Aurora Society est un cercle réservé.",
    chosenMembers: "Chaque membre est choisi.",
    // Profile page
    business: "BUSINESS",
    familySocial: "FAMILY & SOCIAL",
    personal: "PERSONAL",
    influenceNetwork: "RÉSEAUX, INFLUENCE & LIFESTYLE",
    integratedServices: "INTEGRATED SERVICES",
    members: "MEMBRES",
    concierge: "Conciergerie",
    metaverse: "Metaverse",
    marketplace: "Marketplace",
    backToDashboard: "Retour au tableau de bord",
    quote: "Excellence, identity, and distinction define me.",
    // Members page
    back: "Retour",
    export: "Export",
    searchPlaceholder: "Trier par nom, titre, secteur...",
    connectionRequest: "Envoyer une demande de connexion",
    pendingResponse: "⏳ En attente de réponse",
    upgradeRequired: "Mise à niveau requise",
    higherCircle: "Ce membre appartient à un cercle supérieur",
    contactRequirement: "Pour contacter",
    sameLevelRequired: "votre participation doit être de même niveau.",
    requiredLevel: "Niveau requis :",
    amount: "Montant :",
    perMonth: "€/mois",
    validate: "Valider",
    refuse: "Refuser",
    membersShown: "membre",
    membersShownPlural: "membres",
    displayed: "affiché",
    displayedPlural: "affichés",
    sendConnectionRequest: "Souhaitez-vous envoyer une demande de connexion à",
    // Payment page
    payment: "PAIEMENT",
    orderSummary: "Résumé de la commande",
    level: "Niveau",
    monthlySubscription: "Abonnement mensuel",
    accessMembers: "Accès aux membres de votre niveau",
    unlimitedConnections: "Connexions illimitées",
    exclusiveServices: "Services exclusifs Aurora",
    prioritySupport: "Support prioritaire",
    monthlyTotal: "Total mensuel",
    autoRenew: "Renouvelé automatiquement chaque mois",
    paymentInfo: "Informations de paiement",
    cardNumber: "Numéro de carte",
    expirationDate: "Date d'expiration",
    nameOnCard: "Nom sur la carte",
    securePayment: "Vos informations de paiement sont sécurisées et cryptées. Nous ne stockons pas vos données bancaires.",
    confirmPayment: "Confirmer le paiement",
    // Service pages
    conciergePage: "Conciergerie",
    metaversePage: "Metaverse",
    marketplacePage: "Marketplace",
    familyPage: "Famille & Social",
    networkPage: "Réseaux, Influence & Lifestyle",
    backToProfile: "Retour au profil",
    // Security & Settings
    settings: "Paramètres",
    securitySettings: "Sécurité Biométrique",
    biometricSecurity: "Sécurité Biométrique",
    manageAuthMethods: "Gérez vos méthodes d'authentification",
    detectedDevice: "Appareil Détecté",
    autoConfigDevice: "Configuration automatique basée sur votre appareil",
    webBiometricAuth: "Authentification Biométrique Web",
    registeredDevices: "Appareils enregistrés",
    addAnotherDevice: "Ajouter un autre appareil",
    activateBiometric: "Activer",
    configuring: "Configuration en cours...",
    securityTips: "Conseils de sécurité",
    biometricFastSecure: "L'authentification biométrique offre une connexion rapide et sécurisée",
    biometricDataLocal: "Vos données biométriques restent sur votre appareil",
    multipleDevices: "Vous pouvez enregistrer plusieurs appareils",
    passwordFallback: "La connexion par mot de passe reste disponible en cas de besoin",
    logout: "Déconnexion",
    landingPages: "Landing Pages",
    administration: "Administration",
    deleteAccount: "Supprimer le compte",
    homeTagline: "Un cercle privé pour celles et ceux qui veulent conjuguer réussite, art de vivre et sérénité.",
    homeDescription: "Un club international confidentiel dédié aux entrepreneurs, investisseurs et familles fortunées, réunissant opportunités d'affaires, réseau humain, conciergerie de prestige et accès à des actifs rares.",
    homePhilosophy: "« Nous croyons à une approche simple du très haut de gamme : moins d'exposition, plus de qualité. Moins de promesses, plus de résultats. Moins de bruit, plus de relations vraies. »",
    // Connections page
    myConnections: "Mes Connexions",
    connectionCount: "connexion(s)",
    noConnections: "Aucune connexion",
    noConnectionsDescription: "Vous n'avez pas encore de connexions. Explorez le répertoire des membres pour en créer.",
    viewMembers: "Voir les membres",
    sendMessage: "Envoyer un message",
    accessPermissions: "Permissions d'accès",
    permissionsUpdated: "Permissions mises à jour",
    permissionsUpdatedDesc: "Les permissions d'accès ont été modifiées",
    deleteConnection: "Supprimer la connexion ?",
    deleteConnectionDesc: "Cette action supprimera la connexion des deux côtés. Cette action est irréversible.",
    cancel: "Annuler",
    delete: "Supprimer",
    error: "Erreur",
    // Messages page
    unableToSendMessage: "Impossible d'envoyer le message",
    deleteMessage: "Supprimer le message",
    deleteMessageConfirm: "Êtes-vous sûr de vouloir supprimer ce message ? Cette action est irréversible.",
    // Settings page
    settingUpdated: "Paramètre mis à jour",
    preferenceSaved: "Vos préférences ont été enregistrées",
    language: "Langue",
    chooseLanguage: "Choisissez la langue de l'application",
    security: "Sécurité",
    securityDesc: "Paramètres de sécurité de votre compte",
    changePassword: "Changer le mot de passe",
    manageBiometric: "Gérer la sécurité biométrique",
    manageLanding: "Gérer la page d'atterrissage",
    connectionRequests: "Demandes de connexion",
    deleteAccountConfirm: "Supprimer votre compte ?",
    deleteAccountWarning: "Cette action est irréversible. Toutes vos données, connexions, messages et contenus seront définitivement supprimés.",
    deleteForever: "Supprimer définitivement",
    // Concierge page
    availability247: "Disponibilité 24/7",
    availability247Desc: "Notre équipe est à votre service jour et nuit, partout dans le monde",
    globalNetwork: "Réseau Mondial",
    globalNetworkDesc: "Accès à un réseau d'excellence dans plus de 100 villes",
    absoluteConfidentiality: "Confidentialité Absolue",
    absoluteConfidentialityDesc: "Discrétion et sécurité garanties pour tous vos services",
    bespoke: "Sur-Mesure",
    bespokeDesc: "Chaque demande est unique et mérite une attention personnalisée",
    conciergeIntro: "Un service de conciergerie ultra haut de gamme pour organiser, simplifier et sublimer la vie de nos membres.",
    conciergeTagline: "Un seul interlocuteur pour tout ce qui compte réellement.",
    contactConcierge: "Contacter votre concierge",
    readyForExperience: "Prêt à vivre une expérience d'exception ?",
    conciergeExpertDesc: "Notre équipe de concierges experts est à votre disposition pour concrétiser vos demandes les plus exigeantes, où que vous soyez dans le monde.",
    // Marketplace page
    documented: "Documenté",
    documentedDesc: "Traçabilité complète et provenance certifiée",
    secured: "Sécurisé",
    securedDesc: "Transactions confidentielles et garanties",
    presentedWithSobriety: "Présenté avec sobriété",
    presentedWithSobrietyDesc: "Le rare n'est pas exposé, il se transmet entre membres",
    sourcingDesc: "Notre équipe de sourcing est à votre disposition pour rechercher et acquérir les pièces les plus rares selon vos critères",
    contactSourcing: "Contacter le Service de Sourcing",
    // Personal page
    passions: "PASSIONS",
    shareWhatMatters: "Partager ce qui compte vraiment",
    passionsDesc: "Art, gastronomie, automobile, aviation, nautisme, culture, philanthropie — Ce sont souvent les passions qui créent les relations les plus durables.",
    reconfigure: "Reconfigurer",
    // Profile updates
    profileUpdated: "Profil mis à jour avec succès",
    profileUpdateError: "Erreur lors de la mise à jour du profil",
    imageUpdated: "Image mise à jour",
    uploadError: "Erreur lors du téléchargement",
    contentUpdated: "Contenu mis à jour",
    saveError: "Erreur lors de la sauvegarde",
    // Reset password
    updating: "Mise à jour...",
    updatePassword: "Mettre à jour le mot de passe",
    invalidLink: "Lien invalide ou expiré",
    requestNewLink: "Veuillez demander un nouveau lien de réinitialisation.",
    passwordMismatch: "Mots de passe différents",
    passwordMismatchDesc: "Les mots de passe ne correspondent pas.",
    // Login
    loginBiometricFirst: "Veuillez d'abord vous connecter avec votre mot de passe pour activer la biométrie",
    biometricNotEnabled: "La connexion biométrique n'est pas activée pour ce compte. Activez-la dans les paramètres.",
    creating: "Création...",
    createAccount: "Créer mon compte",
    userNotConnected: "Utilisateur non connecté",
    sending: "Envoi...",
    sendLink: "Envoyer le lien",
    // Biometric
    biometricAuth: "Authentification biométrique",
    biometricDesc: "Utilisez la biométrie pour vous connecter rapidement et en toute sécurité.",
    disableBiometric: "Désactiver la biométrie",
    authEnabled: "Authentification activée",
    nowConfigured: "est maintenant configuré pour ce compte",
    unableToActivateBiometric: "Impossible d'activer l'authentification biométrique",
    // WebAuthn
    webAuthnDesc: "Sécurisez l'accès à votre compte avec Touch ID, Face ID ou Windows Hello. Vos données biométriques restent sur votre appareil et ne sont jamais envoyées à nos serveurs.",
    biometricDataStays: "Vos données biométriques restent sur votre appareil",
    instantLogin: "Connexion instantanée à chaque visite",
    enhancedSecurity: "Sécurité renforcée pour votre compte",
    // Onboarding
    configureNetwork: "Configurez votre Réseaux, Influence & Lifestyle",
    configureNetworkDesc: "Choisissez comment vous souhaitez construire votre profil d'influence et de réseau social.",
    aiAurora: "IA Aurora",
    aiAuroraDesc: "Laissez notre IA générer des suggestions personnalisées",
    privateConcierge: "Conciergerie Privée",
    privateConciergeDesc: "Un expert dédié vous accompagne dans la création",
    importFromLinkedIn: "Importer depuis LinkedIn",
    importFromLinkedInDesc: "Connectez votre compte LinkedIn pour importer automatiquement votre réseau professionnel",
    configureFamily: "Configurez votre section Famille & Réseau",
    configureFamilyDesc: "Choisissez comment vous souhaitez construire votre profil familial et réseau. Vous pourrez modifier chaque module individuellement par la suite.",
    aiSuggestions: "Suggestions IA Aurora",
    aiSuggestionsDesc: "Notre IA vous pose quelques questions et génère un profil familial personnalisé",
    privateConciergeAuroraDesc: "Un conseiller Aurora vous contacte pour créer votre profil sur mesure",
    importInfo: "Importer mes informations",
    importInfoDesc: "CV, LinkedIn, bio, site…",
    letAuroraCreate: "Laisser Aurora (IA) faire une première version",
    letAuroraCreateDesc: "Répondez à 3 questions, nous faisons le reste.",
    askConcierge: "Demander à mon contact personnel de s'en charger",
    askConciergeDesc: "Conciergerie privée Aurora.",
    generateProfile: "Générer mon profil",
    indicateSources: "Indiquez vos sources : LinkedIn, site, documents…",
    sourceExample: "Ex: Mon LinkedIn est linkedin.com/in/... Mon site est...",
    infoRequired: "Information requise",
    uploadCvOrLinkedIn: "Veuillez uploader un CV ou entrer une URL LinkedIn.",
    // Admin pages
    adminConnections: "Connexions & Demandes",
    adminConnectionsDesc: "Historique des demandes et relations établies",
    refresh: "Actualiser",
    connectedOn: "Connectés le",
    requests: "Demandes",
    connections: "Connexions",
    noRequestsFound: "Aucune demande trouvée",
    noConnectionsFound: "Aucune connexion trouvée",
    usersSecurity: "Sécurité des Utilisateurs",
    usersSecurityDesc: "Gérez et surveillez les paramètres de sécurité des membres",
    user: "Utilisateur",
    status: "Statut",
    mobileBiometric: "Biométrie Mobile",
    devices: "Appareils",
    securityLevel: "Niveau Sécurité",
    lastActivity: "Dernière activité",
    moderation: "Modération",
    moderationDesc: "Gérez le contenu en attente de validation",
    approvedHistory: "Historique des contenus approuvés",
    rejectedHistory: "Historique des contenus rejetés",
    memberManagement: "Gestion des Membres",
    memberManagementDesc: "Gérez tous les membres de la plateforme",
    deleteMember: "Supprimer ce membre ?",
    deleteMemberDesc: "Cette action est irréversible. Toutes les données seront définitivement supprimées.",
    pendingRequests: "Demandes en attente",
    manageMembers: "Gérer les membres",
    viewAllMembers: "Voir tous les membres",
    manageRoles: "Gérer les rôles",
    assignRoles: "Attribuer des rôles",
    rolesManagement: "Gestion des Rôles",
    rolesManagementDesc: "Attribuez et gérez les rôles administrateur",
    noUserFound: "Aucun utilisateur trouvé",
    activityLogs: "Logs d'Activité",
    activityLogsDesc: "Historique complet des opérations sur la base de données",
    // LinkedAccount
    accountNotFound: "Compte non trouvé",
    // MemberLanding
    loginToContact: "Pour contacter ce membre, veuillez vous connecter à Aurora Society",
    // Registration
    skipStep: "Passer cette étape (votre compte sera limité)",
    // LandingPreview
    contactButton: "Bouton de contact",
    contactButtonDesc: "Permettre aux visiteurs de vous contacter",
    // Contact page
    generalQuestion: "Question générale",
    technicalIssue: "Problème technique",
    accountManagement: "Gestion du compte",
    billing: "Facturation",
    partnership: "Partenariat",
    suggestionFeedback: "Suggestion / Feedback",
    other: "Autre",
    sendingInProgress: "Envoi en cours...",
    sendMessageBtn: "Envoyer le message",
    address: "Adresse",
    manualEntry: "Saisie Manuelle",
    manualEntryDesc: "Compléter moi-même, module par module",
  },
  en: {
    welcome: "Welcome",
    description: "Designed for distinguished members of the global elite, Aurora Society is an application reserved for the most influential personalities.",
    continue: "Continue",
    selectLanguage: "Language",
    register: "Register",
    signIn: "Sign in",
    allRightsReserved: "All rights reserved",
    termsAndConditions: "Terms and Conditions",
    contact: "Contact",
    email: "Email",
    invitationCode: "Invitation code (required)",
    login: "Sign in",
    registration: "REGISTRATION",
    profilePhoto: "Profile Photo",
    referralCode: "Referral Code",
    idCard: "ID Card",
    scanId: "Scan ID Card",
    firstName: "First Name",
    lastName: "Last Name",
    honorificTitle: "Honorific Title",
    mobileNumber: "Mobile Number",
    jobFunction: "Function/Activity",
    activityDomain: "Activity Domain",
    wealthLevel: "Wealth Level",
    personalQuote: "Personal Quote (optional)",
    photoFormatsHint: "Recommended: JPG, PNG or GIF format",
    chooseFile: "Choose a file",
    jobFunctionPlaceholder: "CEO, Chairman, Director...",
    emailPlaceholder: "your@email.com",
    selectTitle: "Select your title",
    selectActivityDomain: "Select your field",
    personalQuotePlaceholder: "To be completed later...",
    founderMember: "Founding Member",
    associatedAccounts: "Associated Accounts",
    acceptTermsPrefix: "I accept the",
    loading: "Loading...",
    exclusiveCircle: "Aurora Society is an exclusive circle.",
    chosenMembers: "Each member is chosen.",
    business: "BUSINESS",
    familySocial: "FAMILY & SOCIAL",
    personal: "PERSONAL",
    influenceNetwork: "NETWORKS, INFLUENCE & LIFESTYLE",
    integratedServices: "INTEGRATED SERVICES",
    members: "MEMBERS",
    concierge: "Concierge",
    metaverse: "Metaverse",
    marketplace: "Marketplace",
    backToDashboard: "Back to dashboard",
    quote: "Excellence, identity, and distinction define me.",
    back: "Back",
    export: "Export",
    searchPlaceholder: "Filter by name, title, sector...",
    connectionRequest: "Send connection request",
    pendingResponse: "⏳ Awaiting response",
    upgradeRequired: "Upgrade required",
    higherCircle: "This member belongs to a higher circle",
    contactRequirement: "To contact",
    sameLevelRequired: "your membership must be of the same level.",
    requiredLevel: "Required level:",
    amount: "Amount:",
    perMonth: "€/month",
    validate: "Validate",
    refuse: "Refuse",
    membersShown: "member",
    membersShownPlural: "members",
    displayed: "displayed",
    displayedPlural: "displayed",
    sendConnectionRequest: "Would you like to send a connection request to",
    payment: "PAYMENT",
    orderSummary: "Order summary",
    level: "Level",
    monthlySubscription: "Monthly subscription",
    accessMembers: "Access to members of your level",
    unlimitedConnections: "Unlimited connections",
    exclusiveServices: "Exclusive Aurora services",
    prioritySupport: "Priority support",
    monthlyTotal: "Monthly total",
    autoRenew: "Automatically renewed each month",
    paymentInfo: "Payment information",
    cardNumber: "Card number",
    expirationDate: "Expiration date",
    nameOnCard: "Name on card",
    securePayment: "Your payment information is secure and encrypted. We do not store your banking data.",
    confirmPayment: "Confirm payment",
    conciergePage: "Concierge",
    metaversePage: "Metaverse",
    marketplacePage: "Marketplace",
    familyPage: "Family & Social",
    networkPage: "Networks, Influence & Lifestyle",
    backToProfile: "Back to profile",
    // Security & Settings
    settings: "Settings",
    securitySettings: "Biometric Security",
    biometricSecurity: "Biometric Security",
    manageAuthMethods: "Manage your authentication methods",
    detectedDevice: "Detected Device",
    autoConfigDevice: "Automatic configuration based on your device",
    webBiometricAuth: "Web Biometric Authentication",
    registeredDevices: "Registered devices",
    addAnotherDevice: "Add another device",
    activateBiometric: "Activate",
    configuring: "Configuring...",
    securityTips: "Security tips",
    biometricFastSecure: "Biometric authentication offers fast and secure login",
    biometricDataLocal: "Your biometric data stays on your device",
    multipleDevices: "You can register multiple devices",
    passwordFallback: "Password login remains available as backup",
    logout: "Logout",
    landingPages: "Landing Pages",
    administration: "Administration",
    deleteAccount: "Delete account",
    homeTagline: "A private circle for those who wish to combine success, art of living and serenity.",
    homeDescription: "A confidential international club dedicated to entrepreneurs, investors and wealthy families, bringing together business opportunities, human network, prestige concierge and access to rare assets.",
    homePhilosophy: "\"We believe in a simple approach to the very high-end: less exposure, more quality. Fewer promises, more results. Less noise, more genuine relationships.\"",
    // Connections page
    myConnections: "My Connections",
    connectionCount: "connection(s)",
    noConnections: "No connections",
    noConnectionsDescription: "You don't have any connections yet. Explore the member directory to create some.",
    viewMembers: "View members",
    sendMessage: "Send message",
    accessPermissions: "Access permissions",
    permissionsUpdated: "Permissions updated",
    permissionsUpdatedDesc: "Access permissions have been modified",
    deleteConnection: "Delete connection?",
    deleteConnectionDesc: "This action will delete the connection from both sides. This action is irreversible.",
    cancel: "Cancel",
    delete: "Delete",
    error: "Error",
    // Messages page
    unableToSendMessage: "Unable to send message",
    deleteMessage: "Delete message",
    deleteMessageConfirm: "Are you sure you want to delete this message? This action is irreversible.",
    // Settings page
    settingUpdated: "Setting updated",
    preferenceSaved: "Your preferences have been saved",
    language: "Language",
    chooseLanguage: "Choose the application language",
    security: "Security",
    securityDesc: "Your account security settings",
    changePassword: "Change password",
    manageBiometric: "Manage biometric security",
    manageLanding: "Manage landing page",
    connectionRequests: "Connection requests",
    deleteAccountConfirm: "Delete your account?",
    deleteAccountWarning: "This action is irreversible. All your data, connections, messages and content will be permanently deleted.",
    deleteForever: "Delete permanently",
    // Concierge page
    availability247: "24/7 Availability",
    availability247Desc: "Our team is at your service day and night, around the world",
    globalNetwork: "Global Network",
    globalNetworkDesc: "Access to a network of excellence in over 100 cities",
    absoluteConfidentiality: "Absolute Confidentiality",
    absoluteConfidentialityDesc: "Discretion and security guaranteed for all your services",
    bespoke: "Bespoke",
    bespokeDesc: "Each request is unique and deserves personalized attention",
    conciergeIntro: "An ultra high-end concierge service to organize, simplify and elevate the lives of our members.",
    conciergeTagline: "One point of contact for everything that truly matters.",
    contactConcierge: "Contact your concierge",
    readyForExperience: "Ready for an exceptional experience?",
    conciergeExpertDesc: "Our team of expert concierges is at your disposal to fulfill your most demanding requests, wherever you are in the world.",
    // Marketplace page
    documented: "Documented",
    documentedDesc: "Complete traceability and certified provenance",
    secured: "Secured",
    securedDesc: "Confidential and guaranteed transactions",
    presentedWithSobriety: "Presented with discretion",
    presentedWithSobrietyDesc: "Rarity is not displayed, it is shared among members",
    sourcingDesc: "Our sourcing team is at your disposal to find and acquire the rarest pieces according to your criteria",
    contactSourcing: "Contact Sourcing Service",
    // Personal page
    passions: "PASSIONS",
    shareWhatMatters: "Share what truly matters",
    passionsDesc: "Art, gastronomy, automobiles, aviation, yachting, culture, philanthropy — Passions often create the most lasting relationships.",
    reconfigure: "Reconfigure",
    // Profile updates
    profileUpdated: "Profile updated successfully",
    profileUpdateError: "Error updating profile",
    imageUpdated: "Image updated",
    uploadError: "Upload error",
    contentUpdated: "Content updated",
    saveError: "Error saving",
    // Reset password
    updating: "Updating...",
    updatePassword: "Update password",
    invalidLink: "Invalid or expired link",
    requestNewLink: "Please request a new reset link.",
    passwordMismatch: "Passwords don't match",
    passwordMismatchDesc: "The passwords do not match.",
    // Login
    loginBiometricFirst: "Please first log in with your password to activate biometrics",
    biometricNotEnabled: "Biometric login is not enabled for this account. Enable it in settings.",
    creating: "Creating...",
    createAccount: "Create my account",
    userNotConnected: "User not connected",
    sending: "Sending...",
    sendLink: "Send link",
    // Biometric
    biometricAuth: "Biometric authentication",
    biometricDesc: "Use biometrics for fast and secure login.",
    disableBiometric: "Disable biometrics",
    authEnabled: "Authentication enabled",
    nowConfigured: "is now configured for this account",
    unableToActivateBiometric: "Unable to activate biometric authentication",
    // WebAuthn
    webAuthnDesc: "Secure access to your account with Touch ID, Face ID or Windows Hello. Your biometric data stays on your device and is never sent to our servers.",
    biometricDataStays: "Your biometric data stays on your device",
    instantLogin: "Instant login on every visit",
    enhancedSecurity: "Enhanced security for your account",
    // Onboarding
    configureNetwork: "Configure your Networks, Influence & Lifestyle",
    configureNetworkDesc: "Choose how you want to build your influence and social network profile.",
    aiAurora: "Aurora AI",
    aiAuroraDesc: "Let our AI generate personalized suggestions",
    privateConcierge: "Private Concierge",
    privateConciergeDesc: "A dedicated expert guides you through the creation",
    importFromLinkedIn: "Import from LinkedIn",
    importFromLinkedInDesc: "Connect your LinkedIn account to automatically import your professional network",
    configureFamily: "Configure your Family & Network section",
    configureFamilyDesc: "Choose how you want to build your family and network profile. You can modify each module individually later.",
    aiSuggestions: "Aurora AI Suggestions",
    aiSuggestionsDesc: "Our AI asks you a few questions and generates a personalized family profile",
    privateConciergeAuroraDesc: "An Aurora advisor will contact you to create your custom profile",
    importInfo: "Import my information",
    importInfoDesc: "Resume, LinkedIn, bio, website…",
    letAuroraCreate: "Let Aurora (AI) create a first version",
    letAuroraCreateDesc: "Answer 3 questions, we do the rest.",
    askConcierge: "Ask my personal contact to handle it",
    askConciergeDesc: "Aurora private concierge.",
    generateProfile: "Generate my profile",
    indicateSources: "Indicate your sources: LinkedIn, website, documents…",
    sourceExample: "Ex: My LinkedIn is linkedin.com/in/... My website is...",
    infoRequired: "Information required",
    uploadCvOrLinkedIn: "Please upload a resume or enter a LinkedIn URL.",
    // Admin pages
    adminConnections: "Connections & Requests",
    adminConnectionsDesc: "History of requests and established relationships",
    refresh: "Refresh",
    connectedOn: "Connected on",
    requests: "Requests",
    connections: "Connections",
    noRequestsFound: "No requests found",
    noConnectionsFound: "No connections found",
    usersSecurity: "Users Security",
    usersSecurityDesc: "Manage and monitor member security settings",
    user: "User",
    status: "Status",
    mobileBiometric: "Mobile Biometric",
    devices: "Devices",
    securityLevel: "Security Level",
    lastActivity: "Last activity",
    moderation: "Moderation",
    moderationDesc: "Manage content awaiting validation",
    approvedHistory: "Approved content history",
    rejectedHistory: "Rejected content history",
    memberManagement: "Member Management",
    memberManagementDesc: "Manage all platform members",
    deleteMember: "Delete this member?",
    deleteMemberDesc: "This action is irreversible. All data will be permanently deleted.",
    pendingRequests: "Pending requests",
    manageMembers: "Manage members",
    viewAllMembers: "View all members",
    manageRoles: "Manage roles",
    assignRoles: "Assign roles",
    rolesManagement: "Roles Management",
    rolesManagementDesc: "Assign and manage administrator roles",
    noUserFound: "No user found",
    activityLogs: "Activity Logs",
    activityLogsDesc: "Complete history of database operations",
    // LinkedAccount
    accountNotFound: "Account not found",
    // MemberLanding
    loginToContact: "To contact this member, please log in to Aurora Society",
    // Registration
    skipStep: "Skip this step (your account will be limited)",
    // LandingPreview
    contactButton: "Contact button",
    contactButtonDesc: "Allow visitors to contact you",
    // Contact page
    generalQuestion: "General question",
    technicalIssue: "Technical issue",
    accountManagement: "Account management",
    billing: "Billing",
    partnership: "Partnership",
    suggestionFeedback: "Suggestion / Feedback",
    other: "Other",
    sendingInProgress: "Sending...",
    sendMessageBtn: "Send message",
    address: "Address",
    manualEntry: "Manual Entry",
    manualEntryDesc: "Complete myself, module by module",
  },
  es: {
    welcome: "Bienvenido",
    description: "Diseñada para miembros distinguidos de la élite mundial, Aurora Society es una aplicación reservada para las personalidades más influyentes.",
    continue: "Continuar",
    selectLanguage: "Idioma",
    register: "Registrarse",
    signIn: "Iniciar sesión",
    allRightsReserved: "Todos los derechos reservados",
    termsAndConditions: "Términos y Condiciones",
    contact: "Contacto",
    email: "Correo electrónico",
    invitationCode: "Código de invitación (obligatorio)",
    login: "Iniciar sesión",
    registration: "REGISTRO",
    profilePhoto: "Foto de Perfil",
    referralCode: "Código de Referido",
    idCard: "Documento de Identidad",
    scanId: "Escanear Documento",
    firstName: "Nombre",
    lastName: "Apellido",
    honorificTitle: "Título Honorífico",
    mobileNumber: "Número de Móvil",
    jobFunction: "Función/Actividad",
    activityDomain: "Área de Actividad",
    wealthLevel: "Nivel de Patrimonio",
    personalQuote: "Cita Personal (opcional)",
    photoFormatsHint: "Formato recomendado: JPG, PNG o GIF",
    chooseFile: "Elegir un archivo",
    jobFunctionPlaceholder: "CEO, Director, Gerente...",
    emailPlaceholder: "tu@email.com",
    selectTitle: "Seleccione su título",
    selectActivityDomain: "Seleccione su área",
    personalQuotePlaceholder: "Para completar más tarde...",
    founderMember: "Miembro Fundador",
    associatedAccounts: "Cuentas Asociadas",
    acceptTermsPrefix: "Acepto los",
    loading: "Cargando...",
    exclusiveCircle: "Aurora Society es un círculo exclusivo.",
    chosenMembers: "Cada miembro es elegido.",
    business: "NEGOCIOS",
    familySocial: "FAMILIA Y SOCIAL",
    personal: "PERSONAL",
    influenceNetwork: "REDES, INFLUENCIA & LIFESTYLE",
    integratedServices: "SERVICIOS INTEGRADOS",
    members: "MIEMBROS",
    concierge: "Conserjería",
    metaverse: "Metaverso",
    marketplace: "Mercado",
    backToDashboard: "Volver al panel",
    quote: "La excelencia, la identidad y la distinción me definen.",
    back: "Volver",
    export: "Exportar",
    searchPlaceholder: "Filtrar por nombre, título, sector...",
    connectionRequest: "Enviar solicitud de conexión",
    pendingResponse: "⏳ Esperando respuesta",
    upgradeRequired: "Actualización requerida",
    higherCircle: "Este miembro pertenece a un círculo superior",
    contactRequirement: "Para contactar",
    sameLevelRequired: "su membresía debe ser del mismo nivel.",
    requiredLevel: "Nivel requerido:",
    amount: "Cantidad:",
    perMonth: "€/mes",
    validate: "Validar",
    refuse: "Rechazar",
    membersShown: "miembro",
    membersShownPlural: "miembros",
    displayed: "mostrado",
    displayedPlural: "mostrados",
    sendConnectionRequest: "¿Desea enviar una solicitud de conexión a",
    payment: "PAGO",
    orderSummary: "Resumen del pedido",
    level: "Nivel",
    monthlySubscription: "Suscripción mensual",
    accessMembers: "Acceso a miembros de su nivel",
    unlimitedConnections: "Conexiones ilimitadas",
    exclusiveServices: "Servicios exclusivos Aurora",
    prioritySupport: "Soporte prioritario",
    monthlyTotal: "Total mensual",
    autoRenew: "Renovado automáticamente cada mes",
    paymentInfo: "Información de pago",
    cardNumber: "Número de tarjeta",
    expirationDate: "Fecha de vencimiento",
    nameOnCard: "Nombre en la tarjeta",
    securePayment: "Su información de pago es segura y encriptada. No almacenamos sus datos bancarios.",
    confirmPayment: "Confirmar pago",
    conciergePage: "Conserjería",
    metaversePage: "Metaverso",
    marketplacePage: "Mercado",
    familyPage: "Familia y Social",
    networkPage: "Redes, Influencia & Lifestyle",
    backToProfile: "Volver al perfil",
    // Security & Settings
    settings: "Configuración",
    securitySettings: "Seguridad Biométrica",
    biometricSecurity: "Seguridad Biométrica",
    manageAuthMethods: "Gestiona tus métodos de autenticación",
    detectedDevice: "Dispositivo Detectado",
    autoConfigDevice: "Configuración automática según tu dispositivo",
    webBiometricAuth: "Autenticación Biométrica Web",
    registeredDevices: "Dispositivos registrados",
    addAnotherDevice: "Añadir otro dispositivo",
    activateBiometric: "Activar",
    configuring: "Configurando...",
    securityTips: "Consejos de seguridad",
    biometricFastSecure: "La autenticación biométrica ofrece un inicio rápido y seguro",
    biometricDataLocal: "Tus datos biométricos permanecen en tu dispositivo",
    multipleDevices: "Puedes registrar múltiples dispositivos",
    passwordFallback: "El inicio con contraseña sigue disponible",
    logout: "Cerrar sesión",
    landingPages: "Páginas de destino",
    administration: "Administración",
    deleteAccount: "Eliminar cuenta",
    homeTagline: "Un círculo privado para quienes desean combinar éxito, arte de vivir y serenidad.",
    homeDescription: "Un club internacional confidencial dedicado a empresarios, inversores y familias adineradas, que reúne oportunidades de negocio, red humana, conserjería de prestigio y acceso a activos exclusivos.",
    homePhilosophy: "«Creemos en un enfoque simple del muy alto nivel: menos exposición, más calidad. Menos promesas, más resultados. Menos ruido, más relaciones auténticas.»",
    // Connections page
    myConnections: "Mis Conexiones",
    connectionCount: "conexión(es)",
    noConnections: "Sin conexiones",
    noConnectionsDescription: "Aún no tienes conexiones. Explora el directorio de miembros para crear algunas.",
    viewMembers: "Ver miembros",
    sendMessage: "Enviar mensaje",
    accessPermissions: "Permisos de acceso",
    permissionsUpdated: "Permisos actualizados",
    permissionsUpdatedDesc: "Los permisos de acceso han sido modificados",
    deleteConnection: "¿Eliminar conexión?",
    deleteConnectionDesc: "Esta acción eliminará la conexión de ambos lados. Esta acción es irreversible.",
    cancel: "Cancelar",
    delete: "Eliminar",
    error: "Error",
    unableToSendMessage: "No se puede enviar el mensaje",
    deleteMessage: "Eliminar mensaje",
    deleteMessageConfirm: "¿Estás seguro de que quieres eliminar este mensaje? Esta acción es irreversible.",
    settingUpdated: "Configuración actualizada",
    preferenceSaved: "Tus preferencias han sido guardadas",
    language: "Idioma",
    chooseLanguage: "Elige el idioma de la aplicación",
    security: "Seguridad",
    securityDesc: "Configuración de seguridad de tu cuenta",
    changePassword: "Cambiar contraseña",
    manageBiometric: "Gestionar seguridad biométrica",
    manageLanding: "Gestionar página de destino",
    connectionRequests: "Solicitudes de conexión",
    deleteAccountConfirm: "¿Eliminar tu cuenta?",
    deleteAccountWarning: "Esta acción es irreversible. Todos tus datos, conexiones, mensajes y contenido serán eliminados permanentemente.",
    deleteForever: "Eliminar permanentemente",
    availability247: "Disponibilidad 24/7",
    availability247Desc: "Nuestro equipo está a tu servicio día y noche, en todo el mundo",
    globalNetwork: "Red Global",
    globalNetworkDesc: "Acceso a una red de excelencia en más de 100 ciudades",
    absoluteConfidentiality: "Confidencialidad Absoluta",
    absoluteConfidentialityDesc: "Discreción y seguridad garantizadas para todos tus servicios",
    bespoke: "A Medida",
    bespokeDesc: "Cada solicitud es única y merece atención personalizada",
    conciergeIntro: "Un servicio de conserjería de ultra alto nivel para organizar, simplificar y elevar la vida de nuestros miembros.",
    conciergeTagline: "Un solo punto de contacto para todo lo que realmente importa.",
    contactConcierge: "Contactar a tu concierge",
    readyForExperience: "¿Listo para una experiencia excepcional?",
    conciergeExpertDesc: "Nuestro equipo de concierges expertos está a tu disposición para cumplir tus solicitudes más exigentes, donde sea que estés en el mundo.",
    documented: "Documentado",
    documentedDesc: "Trazabilidad completa y procedencia certificada",
    secured: "Asegurado",
    securedDesc: "Transacciones confidenciales y garantizadas",
    presentedWithSobriety: "Presentado con discreción",
    presentedWithSobrietyDesc: "Lo raro no se exhibe, se comparte entre miembros",
    sourcingDesc: "Nuestro equipo de sourcing está a tu disposición para encontrar y adquirir las piezas más raras según tus criterios",
    contactSourcing: "Contactar Servicio de Sourcing",
    passions: "PASIONES",
    shareWhatMatters: "Comparte lo que realmente importa",
    passionsDesc: "Arte, gastronomía, automóviles, aviación, yates, cultura, filantropía — Las pasiones a menudo crean las relaciones más duraderas.",
    reconfigure: "Reconfigurar",
    profileUpdated: "Perfil actualizado con éxito",
    profileUpdateError: "Error al actualizar el perfil",
    imageUpdated: "Imagen actualizada",
    uploadError: "Error de carga",
    contentUpdated: "Contenido actualizado",
    saveError: "Error al guardar",
    updating: "Actualizando...",
    updatePassword: "Actualizar contraseña",
    invalidLink: "Enlace inválido o expirado",
    requestNewLink: "Por favor solicita un nuevo enlace de restablecimiento.",
    passwordMismatch: "Las contraseñas no coinciden",
    passwordMismatchDesc: "Las contraseñas no coinciden.",
    loginBiometricFirst: "Por favor, inicia sesión primero con tu contraseña para activar la biometría",
    biometricNotEnabled: "El inicio de sesión biométrico no está habilitado para esta cuenta. Actívalo en configuración.",
    creating: "Creando...",
    createAccount: "Crear mi cuenta",
    userNotConnected: "Usuario no conectado",
    sending: "Enviando...",
    sendLink: "Enviar enlace",
    biometricAuth: "Autenticación biométrica",
    biometricDesc: "Usa la biometría para un inicio de sesión rápido y seguro.",
    disableBiometric: "Desactivar biometría",
    authEnabled: "Autenticación habilitada",
    nowConfigured: "está ahora configurado para esta cuenta",
    unableToActivateBiometric: "No se puede activar la autenticación biométrica",
    webAuthnDesc: "Protege el acceso a tu cuenta con Touch ID, Face ID o Windows Hello. Tus datos biométricos permanecen en tu dispositivo.",
    biometricDataStays: "Tus datos biométricos permanecen en tu dispositivo",
    instantLogin: "Inicio de sesión instantáneo en cada visita",
    enhancedSecurity: "Seguridad mejorada para tu cuenta",
    configureNetwork: "Configura tus Redes, Influencia & Lifestyle",
    configureNetworkDesc: "Elige cómo quieres construir tu perfil de influencia y red social.",
    aiAurora: "IA Aurora",
    aiAuroraDesc: "Deja que nuestra IA genere sugerencias personalizadas",
    privateConcierge: "Conserjería Privada",
    privateConciergeDesc: "Un experto dedicado te guía en la creación",
    importFromLinkedIn: "Importar desde LinkedIn",
    importFromLinkedInDesc: "Conecta tu cuenta de LinkedIn para importar automáticamente tu red profesional",
    configureFamily: "Configura tu sección Familia & Red",
    configureFamilyDesc: "Elige cómo quieres construir tu perfil familiar y de red.",
    aiSuggestions: "Sugerencias IA Aurora",
    aiSuggestionsDesc: "Nuestra IA te hace algunas preguntas y genera un perfil familiar personalizado",
    privateConciergeAuroraDesc: "Un asesor Aurora te contactará para crear tu perfil personalizado",
    importInfo: "Importar mi información",
    importInfoDesc: "CV, LinkedIn, bio, sitio web…",
    letAuroraCreate: "Dejar que Aurora (IA) cree una primera versión",
    letAuroraCreateDesc: "Responde 3 preguntas, nosotros hacemos el resto.",
    askConcierge: "Pedir a mi contacto personal que se encargue",
    askConciergeDesc: "Conserjería privada Aurora.",
    generateProfile: "Generar mi perfil",
    indicateSources: "Indica tus fuentes: LinkedIn, sitio web, documentos…",
    sourceExample: "Ej: Mi LinkedIn es linkedin.com/in/... Mi sitio es...",
    infoRequired: "Información requerida",
    uploadCvOrLinkedIn: "Por favor sube un CV o introduce una URL de LinkedIn.",
    adminConnections: "Conexiones y Solicitudes",
    adminConnectionsDesc: "Historial de solicitudes y relaciones establecidas",
    refresh: "Actualizar",
    connectedOn: "Conectados el",
    requests: "Solicitudes",
    connections: "Conexiones",
    noRequestsFound: "No se encontraron solicitudes",
    noConnectionsFound: "No se encontraron conexiones",
    usersSecurity: "Seguridad de Usuarios",
    usersSecurityDesc: "Gestiona y monitorea la configuración de seguridad de los miembros",
    user: "Usuario",
    status: "Estado",
    mobileBiometric: "Biometría Móvil",
    devices: "Dispositivos",
    securityLevel: "Nivel de Seguridad",
    lastActivity: "Última actividad",
    moderation: "Moderación",
    moderationDesc: "Gestiona el contenido pendiente de validación",
    approvedHistory: "Historial de contenido aprobado",
    rejectedHistory: "Historial de contenido rechazado",
    memberManagement: "Gestión de Miembros",
    memberManagementDesc: "Gestiona todos los miembros de la plataforma",
    deleteMember: "¿Eliminar este miembro?",
    deleteMemberDesc: "Esta acción es irreversible. Todos los datos serán eliminados permanentemente.",
    pendingRequests: "Solicitudes pendientes",
    manageMembers: "Gestionar miembros",
    viewAllMembers: "Ver todos los miembros",
    manageRoles: "Gestionar roles",
    assignRoles: "Asignar roles",
    rolesManagement: "Gestión de Roles",
    rolesManagementDesc: "Asigna y gestiona roles de administrador",
    noUserFound: "No se encontró usuario",
    activityLogs: "Registros de Actividad",
    activityLogsDesc: "Historial completo de operaciones de base de datos",
    accountNotFound: "Cuenta no encontrada",
    loginToContact: "Para contactar a este miembro, inicia sesión en Aurora Society",
    skipStep: "Saltar este paso (tu cuenta será limitada)",
    contactButton: "Botón de contacto",
    contactButtonDesc: "Permitir que los visitantes te contacten",
    generalQuestion: "Pregunta general",
    technicalIssue: "Problema técnico",
    accountManagement: "Gestión de cuenta",
    billing: "Facturación",
    partnership: "Asociación",
    suggestionFeedback: "Sugerencia / Comentario",
    other: "Otro",
    sendingInProgress: "Enviando...",
    sendMessageBtn: "Enviar mensaje",
    address: "Dirección",
    manualEntry: "Entrada Manual",
    manualEntryDesc: "Completar yo mismo, módulo por módulo",
  },
  de: {
    welcome: "Willkommen",
    description: "Entwickelt für angesehene Mitglieder der globalen Elite, ist Aurora Society eine Anwendung, die den einflussreichsten Persönlichkeiten vorbehalten ist.",
    continue: "Weiter",
    selectLanguage: "Sprache",
    register: "Registrieren",
    signIn: "Anmelden",
    allRightsReserved: "Alle Rechte vorbehalten",
    termsAndConditions: "Allgemeine Geschäftsbedingungen",
    contact: "Kontakt",
    email: "E-Mail",
    invitationCode: "Einladungscode (erforderlich)",
    login: "Anmelden",
    registration: "REGISTRIERUNG",
    profilePhoto: "Profilfoto",
    referralCode: "Empfehlungscode",
    idCard: "Ausweis",
    scanId: "Ausweis Scannen",
    firstName: "Vorname",
    lastName: "Nachname",
    honorificTitle: "Ehrentitel",
    mobileNumber: "Mobilnummer",
    jobFunction: "Funktion/Tätigkeit",
    activityDomain: "Tätigkeitsbereich",
    wealthLevel: "Vermögensniveau",
    personalQuote: "Persönliches Zitat (optional)",
    photoFormatsHint: "Empfohlen: JPG, PNG oder GIF",
    chooseFile: "Datei wählen",
    jobFunctionPlaceholder: "CEO, Direktor, Manager...",
    emailPlaceholder: "ihre@email.de",
    selectTitle: "Wählen Sie Ihren Titel",
    selectActivityDomain: "Wählen Sie Ihren Bereich",
    personalQuotePlaceholder: "Später auszufüllen...",
    founderMember: "Gründungsmitglied",
    associatedAccounts: "Verbundene Konten",
    acceptTermsPrefix: "Ich akzeptiere die",
    loading: "Laden...",
    exclusiveCircle: "Aurora Society ist ein exklusiver Kreis.",
    chosenMembers: "Jedes Mitglied wird ausgewählt.",
    business: "GESCHÄFT",
    familySocial: "FAMILIE & SOZIALES",
    personal: "PERSÖNLICH",
    influenceNetwork: "NETZWERKE, EINFLUSS & LIFESTYLE",
    integratedServices: "INTEGRIERTE DIENSTE",
    members: "MITGLIEDER",
    concierge: "Concierge",
    metaverse: "Metaverse",
    marketplace: "Marktplatz",
    backToDashboard: "Zurück zum Dashboard",
    quote: "Exzellenz, Identität und Unterscheidung definieren mich.",
    back: "Zurück",
    export: "Exportieren",
    searchPlaceholder: "Nach Name, Titel, Branche filtern...",
    connectionRequest: "Verbindungsanfrage senden",
    pendingResponse: "⏳ Warte auf Antwort",
    upgradeRequired: "Upgrade erforderlich",
    higherCircle: "Dieses Mitglied gehört zu einem höheren Kreis",
    contactRequirement: "Um Kontakt aufzunehmen",
    sameLevelRequired: "muss Ihre Mitgliedschaft auf derselben Ebene sein.",
    requiredLevel: "Erforderliche Ebene:",
    amount: "Betrag:",
    perMonth: "€/Monat",
    validate: "Bestätigen",
    refuse: "Ablehnen",
    membersShown: "Mitglied",
    membersShownPlural: "Mitglieder",
    displayed: "angezeigt",
    displayedPlural: "angezeigt",
    sendConnectionRequest: "Möchten Sie eine Verbindungsanfrage an senden",
    payment: "ZAHLUNG",
    orderSummary: "Bestellübersicht",
    level: "Ebene",
    monthlySubscription: "Monatliches Abonnement",
    accessMembers: "Zugang zu Mitgliedern Ihrer Ebene",
    unlimitedConnections: "Unbegrenzte Verbindungen",
    exclusiveServices: "Exklusive Aurora-Dienste",
    prioritySupport: "Prioritätsunterstützung",
    monthlyTotal: "Monatliche Summe",
    autoRenew: "Wird jeden Monat automatisch verlängert",
    paymentInfo: "Zahlungsinformationen",
    cardNumber: "Kartennummer",
    expirationDate: "Ablaufdatum",
    nameOnCard: "Name auf der Karte",
    securePayment: "Ihre Zahlungsinformationen sind sicher und verschlüsselt. Wir speichern Ihre Bankdaten nicht.",
    confirmPayment: "Zahlung bestätigen",
    conciergePage: "Concierge",
    metaversePage: "Metaverse",
    marketplacePage: "Marktplatz",
    familyPage: "Familie & Soziales",
    networkPage: "Netzwerke, Einfluss & Lifestyle",
    backToProfile: "Zurück zum Profil",
    // Security & Settings
    settings: "Einstellungen",
    securitySettings: "Biometrische Sicherheit",
    biometricSecurity: "Biometrische Sicherheit",
    manageAuthMethods: "Verwalten Sie Ihre Authentifizierungsmethoden",
    detectedDevice: "Erkanntes Gerät",
    autoConfigDevice: "Automatische Konfiguration basierend auf Ihrem Gerät",
    webBiometricAuth: "Web-Biometrische Authentifizierung",
    registeredDevices: "Registrierte Geräte",
    addAnotherDevice: "Weiteres Gerät hinzufügen",
    activateBiometric: "Aktivieren",
    configuring: "Konfigurieren...",
    securityTips: "Sicherheitstipps",
    biometricFastSecure: "Biometrische Authentifizierung bietet schnelle und sichere Anmeldung",
    biometricDataLocal: "Ihre biometrischen Daten bleiben auf Ihrem Gerät",
    multipleDevices: "Sie können mehrere Geräte registrieren",
    passwordFallback: "Die Passwort-Anmeldung bleibt als Backup verfügbar",
    logout: "Abmelden",
    landingPages: "Landing Pages",
    administration: "Verwaltung",
    deleteAccount: "Konto löschen",
    homeTagline: "Ein privater Kreis für diejenigen, die Erfolg, Lebenskunst und Gelassenheit verbinden möchten.",
    homeDescription: "Ein vertraulicher internationaler Club für Unternehmer, Investoren und wohlhabende Familien, der Geschäftsmöglichkeiten, menschliches Netzwerk, Prestige-Concierge und Zugang zu seltenen Vermögenswerten vereint.",
    homePhilosophy: "«Wir glauben an einen einfachen Ansatz für das absolute Highend: weniger Exposition, mehr Qualität. Weniger Versprechen, mehr Ergebnisse. Weniger Lärm, mehr echte Beziehungen.»",
    // Additional translations
    myConnections: "Meine Verbindungen",
    connectionCount: "Verbindung(en)",
    noConnections: "Keine Verbindungen",
    noConnectionsDescription: "Sie haben noch keine Verbindungen. Erkunden Sie das Mitgliederverzeichnis.",
    viewMembers: "Mitglieder anzeigen",
    sendMessage: "Nachricht senden",
    accessPermissions: "Zugriffsberechtigungen",
    permissionsUpdated: "Berechtigungen aktualisiert",
    permissionsUpdatedDesc: "Die Zugriffsberechtigungen wurden geändert",
    deleteConnection: "Verbindung löschen?",
    deleteConnectionDesc: "Diese Aktion löscht die Verbindung von beiden Seiten. Diese Aktion ist unwiderruflich.",
    cancel: "Abbrechen",
    delete: "Löschen",
    error: "Fehler",
    unableToSendMessage: "Nachricht kann nicht gesendet werden",
    deleteMessage: "Nachricht löschen",
    deleteMessageConfirm: "Sind Sie sicher, dass Sie diese Nachricht löschen möchten?",
    settingUpdated: "Einstellung aktualisiert",
    preferenceSaved: "Ihre Einstellungen wurden gespeichert",
    language: "Sprache",
    chooseLanguage: "Wählen Sie die Anwendungssprache",
    security: "Sicherheit",
    securityDesc: "Sicherheitseinstellungen Ihres Kontos",
    changePassword: "Passwort ändern",
    manageBiometric: "Biometrische Sicherheit verwalten",
    manageLanding: "Landing Page verwalten",
    connectionRequests: "Verbindungsanfragen",
    deleteAccountConfirm: "Konto löschen?",
    deleteAccountWarning: "Diese Aktion ist unwiderruflich. Alle Ihre Daten werden dauerhaft gelöscht.",
    deleteForever: "Dauerhaft löschen",
    availability247: "24/7 Verfügbarkeit",
    availability247Desc: "Unser Team steht Ihnen Tag und Nacht weltweit zur Verfügung",
    globalNetwork: "Globales Netzwerk",
    globalNetworkDesc: "Zugang zu einem Exzellenz-Netzwerk in über 100 Städten",
    absoluteConfidentiality: "Absolute Vertraulichkeit",
    absoluteConfidentialityDesc: "Diskretion und Sicherheit für alle Ihre Dienstleistungen garantiert",
    bespoke: "Maßgeschneidert",
    bespokeDesc: "Jede Anfrage ist einzigartig und verdient persönliche Aufmerksamkeit",
    conciergeIntro: "Ein Ultra-High-End-Concierge-Service für unsere Mitglieder.",
    conciergeTagline: "Ein Ansprechpartner für alles, was wirklich zählt.",
    contactConcierge: "Ihren Concierge kontaktieren",
    readyForExperience: "Bereit für ein außergewöhnliches Erlebnis?",
    conciergeExpertDesc: "Unser Team von Experten-Concierges steht Ihnen zur Verfügung.",
    documented: "Dokumentiert",
    documentedDesc: "Vollständige Rückverfolgbarkeit und zertifizierte Herkunft",
    secured: "Gesichert",
    securedDesc: "Vertrauliche und garantierte Transaktionen",
    presentedWithSobriety: "Mit Diskretion präsentiert",
    presentedWithSobrietyDesc: "Seltenheit wird nicht ausgestellt, sie wird unter Mitgliedern geteilt",
    sourcingDesc: "Unser Sourcing-Team steht Ihnen zur Verfügung",
    contactSourcing: "Sourcing-Service kontaktieren",
    passions: "LEIDENSCHAFTEN",
    shareWhatMatters: "Teilen Sie, was wirklich zählt",
    passionsDesc: "Kunst, Gastronomie, Automobile... Leidenschaften schaffen oft die dauerhaftesten Beziehungen.",
    reconfigure: "Neu konfigurieren",
    profileUpdated: "Profil erfolgreich aktualisiert",
    profileUpdateError: "Fehler beim Aktualisieren des Profils",
    imageUpdated: "Bild aktualisiert",
    uploadError: "Upload-Fehler",
    contentUpdated: "Inhalt aktualisiert",
    saveError: "Fehler beim Speichern",
    updating: "Aktualisieren...",
    updatePassword: "Passwort aktualisieren",
    invalidLink: "Ungültiger oder abgelaufener Link",
    requestNewLink: "Bitte fordern Sie einen neuen Reset-Link an.",
    passwordMismatch: "Passwörter stimmen nicht überein",
    passwordMismatchDesc: "Die Passwörter stimmen nicht überein.",
    loginBiometricFirst: "Bitte melden Sie sich zuerst mit Ihrem Passwort an",
    biometricNotEnabled: "Biometrische Anmeldung ist für dieses Konto nicht aktiviert.",
    creating: "Erstellen...",
    createAccount: "Mein Konto erstellen",
    userNotConnected: "Benutzer nicht verbunden",
    sending: "Senden...",
    sendLink: "Link senden",
    biometricAuth: "Biometrische Authentifizierung",
    biometricDesc: "Verwenden Sie Biometrie für schnelle und sichere Anmeldung.",
    disableBiometric: "Biometrie deaktivieren",
    authEnabled: "Authentifizierung aktiviert",
    nowConfigured: "ist jetzt für dieses Konto konfiguriert",
    unableToActivateBiometric: "Biometrische Authentifizierung kann nicht aktiviert werden",
    webAuthnDesc: "Sichern Sie den Zugang mit Touch ID, Face ID oder Windows Hello.",
    biometricDataStays: "Ihre biometrischen Daten bleiben auf Ihrem Gerät",
    instantLogin: "Sofortige Anmeldung bei jedem Besuch",
    enhancedSecurity: "Verbesserte Sicherheit für Ihr Konto",
    configureNetwork: "Konfigurieren Sie Ihre Netzwerke",
    configureNetworkDesc: "Wählen Sie, wie Sie Ihr Profil erstellen möchten.",
    aiAurora: "Aurora KI",
    aiAuroraDesc: "Lassen Sie unsere KI personalisierte Vorschläge generieren",
    privateConcierge: "Privater Concierge",
    privateConciergeDesc: "Ein Experte begleitet Sie bei der Erstellung",
    importFromLinkedIn: "Von LinkedIn importieren",
    importFromLinkedInDesc: "Verbinden Sie Ihr LinkedIn-Konto",
    configureFamily: "Konfigurieren Sie Ihre Familie & Netzwerk Sektion",
    configureFamilyDesc: "Wählen Sie, wie Sie Ihr Familienprofil erstellen möchten.",
    aiSuggestions: "Aurora KI Vorschläge",
    aiSuggestionsDesc: "Unsere KI stellt Ihnen einige Fragen",
    privateConciergeAuroraDesc: "Ein Aurora-Berater wird Sie kontaktieren",
    importInfo: "Meine Informationen importieren",
    importInfoDesc: "Lebenslauf, LinkedIn, Bio, Website…",
    letAuroraCreate: "Aurora (KI) eine erste Version erstellen lassen",
    letAuroraCreateDesc: "Beantworten Sie 3 Fragen, wir machen den Rest.",
    askConcierge: "Meinen persönlichen Kontakt beauftragen",
    askConciergeDesc: "Aurora privater Concierge.",
    generateProfile: "Mein Profil generieren",
    indicateSources: "Geben Sie Ihre Quellen an",
    sourceExample: "Z.B.: Mein LinkedIn ist linkedin.com/in/...",
    infoRequired: "Information erforderlich",
    uploadCvOrLinkedIn: "Bitte laden Sie einen Lebenslauf hoch oder geben Sie eine LinkedIn-URL ein.",
    adminConnections: "Verbindungen & Anfragen",
    adminConnectionsDesc: "Verlauf der Anfragen und etablierten Beziehungen",
    refresh: "Aktualisieren",
    connectedOn: "Verbunden am",
    requests: "Anfragen",
    connections: "Verbindungen",
    noRequestsFound: "Keine Anfragen gefunden",
    noConnectionsFound: "Keine Verbindungen gefunden",
    usersSecurity: "Benutzersicherheit",
    usersSecurityDesc: "Verwalten Sie die Sicherheitseinstellungen der Mitglieder",
    user: "Benutzer",
    status: "Status",
    mobileBiometric: "Mobile Biometrie",
    devices: "Geräte",
    securityLevel: "Sicherheitsstufe",
    lastActivity: "Letzte Aktivität",
    moderation: "Moderation",
    moderationDesc: "Inhalte zur Validierung verwalten",
    approvedHistory: "Genehmigte Inhalte",
    rejectedHistory: "Abgelehnte Inhalte",
    memberManagement: "Mitgliederverwaltung",
    memberManagementDesc: "Alle Plattformmitglieder verwalten",
    deleteMember: "Dieses Mitglied löschen?",
    deleteMemberDesc: "Diese Aktion ist unwiderruflich.",
    pendingRequests: "Ausstehende Anfragen",
    manageMembers: "Mitglieder verwalten",
    viewAllMembers: "Alle Mitglieder anzeigen",
    manageRoles: "Rollen verwalten",
    assignRoles: "Rollen zuweisen",
    rolesManagement: "Rollenverwaltung",
    rolesManagementDesc: "Administrator-Rollen zuweisen und verwalten",
    noUserFound: "Kein Benutzer gefunden",
    activityLogs: "Aktivitätsprotokolle",
    activityLogsDesc: "Vollständiger Verlauf der Datenbankoperationen",
    accountNotFound: "Konto nicht gefunden",
    loginToContact: "Um dieses Mitglied zu kontaktieren, melden Sie sich bitte an",
    skipStep: "Diesen Schritt überspringen (Ihr Konto wird eingeschränkt)",
    contactButton: "Kontakt-Button",
    contactButtonDesc: "Besuchern erlauben, Sie zu kontaktieren",
    generalQuestion: "Allgemeine Frage",
    technicalIssue: "Technisches Problem",
    accountManagement: "Kontoverwaltung",
    billing: "Abrechnung",
    partnership: "Partnerschaft",
    suggestionFeedback: "Vorschlag / Feedback",
    other: "Andere",
    sendingInProgress: "Wird gesendet...",
    sendMessageBtn: "Nachricht senden",
    address: "Adresse",
    manualEntry: "Manuelle Eingabe",
    manualEntryDesc: "Selbst ausfüllen, Modul für Modul",
  },
  it: {
    welcome: "Benvenuto",
    description: "Progettata per membri distinti dell'élite globale, Aurora Society è un'applicazione riservata alle personalità più influenti.",
    continue: "Continua",
    selectLanguage: "Lingua",
    register: "Registrati",
    signIn: "Accedi",
    allRightsReserved: "Tutti i diritti riservati",
    termsAndConditions: "Termini e Condizioni",
    contact: "Contatto",
    email: "Email",
    invitationCode: "Codice di invito (obbligatorio)",
    login: "Accedi",
    registration: "REGISTRAZIONE",
    profilePhoto: "Foto Profilo",
    referralCode: "Codice Referral",
    idCard: "Documento d'Identità",
    scanId: "Scansiona Documento",
    firstName: "Nome",
    lastName: "Cognome",
    honorificTitle: "Titolo Onorifico",
    mobileNumber: "Numero di Cellulare",
    jobFunction: "Funzione/Attività",
    activityDomain: "Settore di Attività",
    wealthLevel: "Livello di Patrimonio",
    personalQuote: "Citazione Personale (opzionale)",
    photoFormatsHint: "Formato consigliato: JPG, PNG o GIF",
    chooseFile: "Scegli un file",
    jobFunctionPlaceholder: "CEO, Direttore, Manager...",
    emailPlaceholder: "tua@email.it",
    selectTitle: "Seleziona il tuo titolo",
    selectActivityDomain: "Seleziona il tuo settore",
    personalQuotePlaceholder: "Da compilare più tardi...",
    founderMember: "Membro Fondatore",
    associatedAccounts: "Account Associati",
    acceptTermsPrefix: "Accetto i",
    loading: "Caricamento...",
    exclusiveCircle: "Aurora Society è un circolo esclusivo.",
    chosenMembers: "Ogni membro è scelto.",
    business: "AFFARI",
    familySocial: "FAMIGLIA E SOCIALE",
    personal: "PERSONALE",
    influenceNetwork: "RETI, INFLUENZA & LIFESTYLE",
    integratedServices: "SERVIZI INTEGRATI",
    members: "MEMBRI",
    concierge: "Concierge",
    metaverse: "Metaverso",
    marketplace: "Mercato",
    backToDashboard: "Torna alla dashboard",
    quote: "L'eccellenza, l'identità e la distinzione mi definiscono.",
    back: "Indietro",
    export: "Esporta",
    searchPlaceholder: "Filtra per nome, titolo, settore...",
    connectionRequest: "Invia richiesta di connessione",
    pendingResponse: "⏳ In attesa di risposta",
    upgradeRequired: "Aggiornamento richiesto",
    higherCircle: "Questo membro appartiene a un circolo superiore",
    contactRequirement: "Per contattare",
    sameLevelRequired: "la tua iscrizione deve essere dello stesso livello.",
    requiredLevel: "Livello richiesto:",
    amount: "Importo:",
    perMonth: "€/mese",
    validate: "Convalida",
    refuse: "Rifiuta",
    membersShown: "membro",
    membersShownPlural: "membri",
    displayed: "visualizzato",
    displayedPlural: "visualizzati",
    sendConnectionRequest: "Desideri inviare una richiesta di connessione a",
    payment: "PAGAMENTO",
    orderSummary: "Riepilogo ordine",
    level: "Livello",
    monthlySubscription: "Abbonamento mensile",
    accessMembers: "Accesso ai membri del tuo livello",
    unlimitedConnections: "Connessioni illimitate",
    exclusiveServices: "Servizi esclusivi Aurora",
    prioritySupport: "Supporto prioritario",
    monthlyTotal: "Totale mensile",
    autoRenew: "Rinnovato automaticamente ogni mese",
    paymentInfo: "Informazioni di pagamento",
    cardNumber: "Numero carta",
    expirationDate: "Data di scadenza",
    nameOnCard: "Nome sulla carta",
    securePayment: "Le tue informazioni di pagamento sono sicure e crittografate. Non memorizziamo i tuoi dati bancari.",
    confirmPayment: "Conferma pagamento",
    conciergePage: "Concierge",
    metaversePage: "Metaverso",
    marketplacePage: "Mercato",
    familyPage: "Famiglia e Sociale",
    networkPage: "Reti, Influenza & Lifestyle",
    backToProfile: "Torna al profilo",
    // Security & Settings
    settings: "Impostazioni",
    securitySettings: "Sicurezza Biometrica",
    biometricSecurity: "Sicurezza Biometrica",
    manageAuthMethods: "Gestisci i tuoi metodi di autenticazione",
    detectedDevice: "Dispositivo Rilevato",
    autoConfigDevice: "Configurazione automatica basata sul tuo dispositivo",
    webBiometricAuth: "Autenticazione Biometrica Web",
    registeredDevices: "Dispositivi registrati",
    addAnotherDevice: "Aggiungi un altro dispositivo",
    activateBiometric: "Attiva",
    configuring: "Configurazione...",
    securityTips: "Consigli di sicurezza",
    biometricFastSecure: "L'autenticazione biometrica offre un accesso rapido e sicuro",
    biometricDataLocal: "I tuoi dati biometrici rimangono sul tuo dispositivo",
    multipleDevices: "Puoi registrare più dispositivi",
    passwordFallback: "L'accesso con password rimane disponibile",
    logout: "Disconnetti",
    landingPages: "Pagine di Destinazione",
    administration: "Amministrazione",
    deleteAccount: "Elimina account",
    homeTagline: "Un circolo privato per coloro che desiderano coniugare successo, arte di vivere e serenità.",
    homeDescription: "Un club internazionale riservato dedicato a imprenditori, investitori e famiglie facoltose, che riunisce opportunità di business, rete umana, concierge di prestigio e accesso a beni rari.",
    homePhilosophy: "«Crediamo in un approccio semplice all'altissima gamma: meno esposizione, più qualità. Meno promesse, più risultati. Meno rumore, più relazioni autentiche.»",
  },
  pt: {
    welcome: "Bem-vindo",
    description: "Projetada para membros distintos da elite global, Aurora Society é uma aplicação reservada para as personalidades mais influentes.",
    continue: "Continuar",
    selectLanguage: "Idioma",
    register: "Registrar",
    signIn: "Entrar",
    allRightsReserved: "Todos os direitos reservados",
    termsAndConditions: "Termos e Condições",
    contact: "Contato",
    email: "Email",
    invitationCode: "Código de convite (obrigatório)",
    login: "Entrar",
    registration: "REGISTRO",
    profilePhoto: "Foto de Perfil",
    referralCode: "Código de Indicação",
    idCard: "Documento de Identidade",
    scanId: "Escanear Documento",
    firstName: "Nome",
    lastName: "Sobrenome",
    honorificTitle: "Título Honorífico",
    mobileNumber: "Número de Celular",
    jobFunction: "Função/Atividade",
    activityDomain: "Área de Atuação",
    wealthLevel: "Nível de Patrimônio",
    personalQuote: "Citação Pessoal (opcional)",
    photoFormatsHint: "Formato recomendado: JPG, PNG ou GIF",
    chooseFile: "Escolher um arquivo",
    jobFunctionPlaceholder: "CEO, Diretor, Gerente...",
    emailPlaceholder: "seu@email.com",
    selectTitle: "Selecione seu título",
    selectActivityDomain: "Selecione sua área",
    personalQuotePlaceholder: "Para preencher mais tarde...",
    founderMember: "Membro Fundador",
    associatedAccounts: "Contas Associadas",
    acceptTermsPrefix: "Aceito os",
    loading: "Carregando...",
    exclusiveCircle: "Aurora Society é um círculo exclusivo.",
    chosenMembers: "Cada membro é escolhido.",
    business: "NEGÓCIOS",
    familySocial: "FAMÍLIA E SOCIAL",
    personal: "PESSOAL",
    influenceNetwork: "REDES, INFLUÊNCIA & LIFESTYLE",
    integratedServices: "SERVIÇOS INTEGRADOS",
    members: "MEMBROS",
    concierge: "Concierge",
    metaverse: "Metaverso",
    marketplace: "Mercado",
    backToDashboard: "Voltar ao painel",
    quote: "Excelência, identidade e distinção me definem.",
    back: "Voltar",
    export: "Exportar",
    searchPlaceholder: "Filtrar por nome, título, setor...",
    connectionRequest: "Enviar pedido de conexão",
    pendingResponse: "⏳ Aguardando resposta",
    upgradeRequired: "Atualização necessária",
    higherCircle: "Este membro pertence a um círculo superior",
    contactRequirement: "Para contactar",
    sameLevelRequired: "sua assinatura deve ser do mesmo nível.",
    requiredLevel: "Nível necessário:",
    amount: "Valor:",
    perMonth: "€/mês",
    validate: "Validar",
    refuse: "Recusar",
    membersShown: "membro",
    membersShownPlural: "membros",
    displayed: "exibido",
    displayedPlural: "exibidos",
    sendConnectionRequest: "Gostaria de enviar um pedido de conexão para",
    payment: "PAGAMENTO",
    orderSummary: "Resumo do pedido",
    level: "Nível",
    monthlySubscription: "Assinatura mensal",
    accessMembers: "Acesso a membros do seu nível",
    unlimitedConnections: "Conexões ilimitadas",
    exclusiveServices: "Serviços exclusivos Aurora",
    prioritySupport: "Suporte prioritário",
    monthlyTotal: "Total mensal",
    autoRenew: "Renovado automaticamente a cada mês",
    paymentInfo: "Informações de pagamento",
    cardNumber: "Número do cartão",
    expirationDate: "Data de validade",
    nameOnCard: "Nome no cartão",
    securePayment: "Suas informações de pagamento são seguras e criptografadas. Não armazenamos seus dados bancários.",
    confirmPayment: "Confirmar pagamento",
    conciergePage: "Concierge",
    metaversePage: "Metaverso",
    marketplacePage: "Mercado",
    familyPage: "Família e Social",
    networkPage: "Redes, Influência & Lifestyle",
    backToProfile: "Voltar ao perfil",
    // Security & Settings
    settings: "Configurações",
    securitySettings: "Segurança Biométrica",
    biometricSecurity: "Segurança Biométrica",
    manageAuthMethods: "Gerencie seus métodos de autenticação",
    detectedDevice: "Dispositivo Detectado",
    autoConfigDevice: "Configuração automática baseada no seu dispositivo",
    webBiometricAuth: "Autenticação Biométrica Web",
    registeredDevices: "Dispositivos registrados",
    addAnotherDevice: "Adicionar outro dispositivo",
    activateBiometric: "Ativar",
    configuring: "Configurando...",
    securityTips: "Dicas de segurança",
    biometricFastSecure: "A autenticação biométrica oferece login rápido e seguro",
    biometricDataLocal: "Seus dados biométricos permanecem no seu dispositivo",
    multipleDevices: "Você pode registrar múltiplos dispositivos",
    passwordFallback: "O login por senha permanece disponível",
    logout: "Sair",
    landingPages: "Páginas de Destino",
    administration: "Administração",
    deleteAccount: "Excluir conta",
    homeTagline: "Um círculo privado para aqueles que desejam combinar sucesso, arte de viver e serenidade.",
    homeDescription: "Um clube internacional confidencial dedicado a empresários, investidores e famílias abastadas, reunindo oportunidades de negócios, rede humana, concierge de prestígio e acesso a ativos raros.",
    homePhilosophy: "«Acreditamos numa abordagem simples do muito alto padrão: menos exposição, mais qualidade. Menos promessas, mais resultados. Menos ruído, mais relações genuínas.»",
  },
  ar: {
    welcome: "مرحباً",
    description: "مصممة لأعضاء النخبة العالمية المتميزين، Aurora Society هو تطبيق مخصص للشخصيات الأكثر نفوذاً.",
    continue: "متابعة",
    selectLanguage: "اللغة",
    register: "التسجيل",
    signIn: "تسجيل الدخول",
    allRightsReserved: "جميع الحقوق محفوظة",
    termsAndConditions: "الشروط والأحكام",
    contact: "اتصل بنا",
    email: "البريد الإلكتروني",
    invitationCode: "كود الدعوة (مطلوب)",
    login: "تسجيل الدخول",
    registration: "التسجيل",
    profilePhoto: "صورة الملف الشخصي",
    referralCode: "كود الإحالة",
    idCard: "بطاقة الهوية",
    scanId: "مسح البطاقة",
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    honorificTitle: "اللقب الفخري",
    mobileNumber: "رقم الجوال",
    jobFunction: "الوظيفة/النشاط",
    activityDomain: "مجال النشاط",
    wealthLevel: "مستوى الثروة",
    personalQuote: "اقتباس شخصي (اختياري)",
    photoFormatsHint: "الصيغة الموصى بها: JPG أو PNG أو GIF",
    chooseFile: "اختر ملف",
    jobFunctionPlaceholder: "الرئيس التنفيذي، المدير...",
    emailPlaceholder: "بريدك@الإلكتروني.com",
    selectTitle: "اختر لقبك",
    selectActivityDomain: "اختر مجالك",
    personalQuotePlaceholder: "للملء لاحقاً...",
    founderMember: "عضو مؤسس",
    associatedAccounts: "الحسابات المرتبطة",
    acceptTermsPrefix: "أوافق على",
    loading: "جاري التحميل...",
    exclusiveCircle: "Aurora Society هي دائرة حصرية.",
    chosenMembers: "يتم اختيار كل عضو.",
    business: "الأعمال",
    familySocial: "العائلة والاجتماعية",
    personal: "شخصي",
    influenceNetwork: "الشبكات والتأثير ونمط الحياة",
    integratedServices: "الخدمات المتكاملة",
    members: "الأعضاء",
    concierge: "الكونسيرج",
    metaverse: "الميتافيرس",
    marketplace: "السوق",
    backToDashboard: "العودة إلى لوحة التحكم",
    quote: "التميز والهوية والتفرد يحددونني.",
    back: "رجوع",
    export: "تصدير",
    searchPlaceholder: "تصفية حسب الاسم، اللقب، القطاع...",
    connectionRequest: "إرسال طلب اتصال",
    pendingResponse: "⏳ في انتظار الرد",
    upgradeRequired: "التحديث مطلوب",
    higherCircle: "هذا العضو ينتمي إلى دائرة أعلى",
    contactRequirement: "للاتصال",
    sameLevelRequired: "يجب أن تكون عضويتك من نفس المستوى.",
    requiredLevel: "المستوى المطلوب:",
    amount: "المبلغ:",
    perMonth: "€/شهر",
    validate: "تأكيد",
    refuse: "رفض",
    membersShown: "عضو",
    membersShownPlural: "أعضاء",
    displayed: "معروض",
    displayedPlural: "معروضة",
    sendConnectionRequest: "هل ترغب في إرسال طلب اتصال إلى",
    payment: "الدفع",
    orderSummary: "ملخص الطلب",
    level: "المستوى",
    monthlySubscription: "اشتراك شهري",
    accessMembers: "الوصول إلى أعضاء مستواك",
    unlimitedConnections: "اتصالات غير محدودة",
    exclusiveServices: "خدمات Aurora الحصرية",
    prioritySupport: "دعم ذو أولوية",
    monthlyTotal: "المجموع الشهري",
    autoRenew: "يتم التجديد تلقائيًا كل شهر",
    paymentInfo: "معلومات الدفع",
    cardNumber: "رقم البطاقة",
    expirationDate: "تاريخ الانتهاء",
    nameOnCard: "الاسم على البطاقة",
    securePayment: "معلومات الدفع الخاصة بك آمنة ومشفرة. نحن لا نخزن بياناتك المصرفية.",
    confirmPayment: "تأكيد الدفع",
    conciergePage: "الكونسيرج",
    metaversePage: "الميتافيرس",
    marketplacePage: "السوق",
    familyPage: "العائلة والاجتماعية",
    networkPage: "الشبكات والتأثير ونمط الحياة",
    backToProfile: "العودة إلى الملف الشخصي",
    // Security & Settings
    settings: "الإعدادات",
    securitySettings: "الأمان البيومتري",
    biometricSecurity: "الأمان البيومتري",
    manageAuthMethods: "إدارة طرق المصادقة الخاصة بك",
    detectedDevice: "الجهاز المكتشف",
    autoConfigDevice: "تكوين تلقائي بناءً على جهازك",
    webBiometricAuth: "المصادقة البيومترية عبر الويب",
    registeredDevices: "الأجهزة المسجلة",
    addAnotherDevice: "إضافة جهاز آخر",
    activateBiometric: "تفعيل",
    configuring: "جاري التكوين...",
    securityTips: "نصائح أمنية",
    biometricFastSecure: "توفر المصادقة البيومترية تسجيل دخول سريع وآمن",
    biometricDataLocal: "تبقى بياناتك البيومترية على جهازك",
    multipleDevices: "يمكنك تسجيل أجهزة متعددة",
    passwordFallback: "يظل تسجيل الدخول بكلمة المرور متاحاً",
    logout: "تسجيل الخروج",
    landingPages: "صفحات الهبوط",
    administration: "الإدارة",
    deleteAccount: "حذف الحساب",
    homeTagline: "دائرة خاصة لأولئك الذين يرغبون في الجمع بين النجاح وفن العيش والسكينة.",
    homeDescription: "نادٍ دولي سري مخصص لرجال الأعمال والمستثمرين والعائلات الثرية، يجمع بين فرص الأعمال والشبكة البشرية وخدمات الكونسيرج الفاخرة والوصول إلى الأصول النادرة.",
    homePhilosophy: "«نؤمن بنهج بسيط للرفاهية المطلقة: تعرض أقل، جودة أعلى. وعود أقل، نتائج أكثر. ضوضاء أقل، علاقات حقيقية أكثر.»",
  },
  zh: {
    welcome: "欢迎",
    description: "专为全球精英尊贵会员设计，Aurora Society是一款专为最具影响力人物保留的应用程序。",
    continue: "继续",
    selectLanguage: "语言",
    register: "注册",
    signIn: "登录",
    allRightsReserved: "版权所有",
    termsAndConditions: "条款和条件",
    contact: "联系我们",
    email: "电子邮件",
    invitationCode: "邀请码（必需）",
    login: "登录",
    registration: "注册",
    profilePhoto: "个人照片",
    referralCode: "推荐码",
    idCard: "身份证",
    scanId: "扫描身份证",
    firstName: "名",
    lastName: "姓",
    honorificTitle: "荣誉头衔",
    mobileNumber: "手机号码",
    jobFunction: "职能/活动",
    activityDomain: "活动领域",
    wealthLevel: "财富水平",
    personalQuote: "个人语录（可选）",
    photoFormatsHint: "推荐格式：JPG、PNG 或 GIF",
    chooseFile: "选择文件",
    jobFunctionPlaceholder: "CEO、董事、经理...",
    emailPlaceholder: "您的@邮箱.com",
    selectTitle: "选择您的头衔",
    selectActivityDomain: "选择您的领域",
    personalQuotePlaceholder: "稍后填写...",
    founderMember: "创始会员",
    associatedAccounts: "关联账户",
    acceptTermsPrefix: "我接受",
    loading: "加载中...",
    exclusiveCircle: "Aurora Society是一个专属圈子。",
    chosenMembers: "每位成员都经过精心挑选。",
    business: "商务",
    familySocial: "家庭与社交",
    personal: "个人",
    influenceNetwork: "网络、影响力与生活方式",
    integratedServices: "集成服务",
    members: "成员",
    concierge: "礼宾服务",
    metaverse: "元宇宙",
    marketplace: "市场",
    backToDashboard: "返回仪表板",
    quote: "卓越、身份和独特性定义了我。",
    back: "返回",
    export: "导出",
    searchPlaceholder: "按姓名、职位、行业筛选...",
    connectionRequest: "发送连接请求",
    pendingResponse: "⏳ 等待回复",
    upgradeRequired: "需要升级",
    higherCircle: "该成员属于更高级别圈子",
    contactRequirement: "要联系",
    sameLevelRequired: "您的会员级别必须相同。",
    requiredLevel: "所需级别：",
    amount: "金额：",
    perMonth: "€/月",
    validate: "确认",
    refuse: "拒绝",
    membersShown: "成员",
    membersShownPlural: "成员",
    displayed: "已显示",
    displayedPlural: "已显示",
    sendConnectionRequest: "您想向以下人员发送连接请求吗",
    payment: "付款",
    orderSummary: "订单摘要",
    level: "级别",
    monthlySubscription: "月度订阅",
    accessMembers: "访问您级别的成员",
    unlimitedConnections: "无限连接",
    exclusiveServices: "Aurora专属服务",
    prioritySupport: "优先支持",
    monthlyTotal: "每月总计",
    autoRenew: "每月自动续订",
    paymentInfo: "付款信息",
    cardNumber: "卡号",
    expirationDate: "有效期",
    nameOnCard: "持卡人姓名",
    securePayment: "您的付款信息是安全加密的。我们不会存储您的银行数据。",
    confirmPayment: "确认付款",
    conciergePage: "礼宾服务",
    metaversePage: "元宇宙",
    marketplacePage: "市场",
    familyPage: "家庭与社交",
    networkPage: "网络、影响力与生活方式",
    backToProfile: "返回个人资料",
    // Security & Settings
    settings: "设置",
    securitySettings: "生物识别安全",
    biometricSecurity: "生物识别安全",
    manageAuthMethods: "管理您的身份验证方式",
    detectedDevice: "检测到的设备",
    autoConfigDevice: "根据您的设备自动配置",
    webBiometricAuth: "网页生物识别认证",
    registeredDevices: "已注册设备",
    addAnotherDevice: "添加其他设备",
    activateBiometric: "激活",
    configuring: "配置中...",
    securityTips: "安全提示",
    biometricFastSecure: "生物识别认证提供快速安全的登录",
    biometricDataLocal: "您的生物识别数据保存在设备上",
    multipleDevices: "您可以注册多个设备",
    passwordFallback: "密码登录仍然可用",
    logout: "退出登录",
    landingPages: "落地页",
    administration: "管理",
    deleteAccount: "删除账户",
    homeTagline: "一个专为追求成功、生活艺术与内心平静的人士打造的私密圈子。",
    homeDescription: "一个为企业家、投资者和富裕家庭打造的国际私密俱乐部，汇聚商业机会、人脉网络、尊享礼宾服务及稀有资产。",
    homePhilosophy: "「我们信奉简约的顶级理念：更少曝光，更多品质。更少承诺，更多成果。更少喧嚣，更多真诚关系。」",
  },
  ja: {
    welcome: "ようこそ",
    description: "世界のエリートメンバーのために設計されたAurora Societyは、最も影響力のある人物のために予約されたアプリケーションです。",
    continue: "続ける",
    selectLanguage: "言語",
    register: "登録",
    signIn: "ログイン",
    allRightsReserved: "すべての権利を保有",
    termsAndConditions: "利用規約",
    contact: "お問い合わせ",
    email: "メールアドレス",
    invitationCode: "招待コード（必須）",
    login: "ログイン",
    registration: "登録",
    profilePhoto: "プロフィール写真",
    referralCode: "紹介コード",
    idCard: "身分証明書",
    scanId: "身分証明書をスキャン",
    firstName: "名",
    lastName: "姓",
    honorificTitle: "敬称",
    mobileNumber: "携帯電話番号",
    jobFunction: "職務/活動",
    activityDomain: "活動分野",
    wealthLevel: "資産レベル",
    personalQuote: "個人的な引用（オプション）",
    photoFormatsHint: "推奨形式：JPG、PNG、GIF",
    chooseFile: "ファイルを選択",
    jobFunctionPlaceholder: "CEO、ディレクター、マネージャー...",
    emailPlaceholder: "あなたの@メール.com",
    selectTitle: "タイトルを選択",
    selectActivityDomain: "分野を選択",
    personalQuotePlaceholder: "後で記入...",
    founderMember: "創設メンバー",
    associatedAccounts: "関連アカウント",
    acceptTermsPrefix: "同意します",
    loading: "読み込み中...",
    exclusiveCircle: "Aurora Societyは限定的なサークルです。",
    chosenMembers: "各メンバーは選ばれています。",
    business: "ビジネス",
    familySocial: "家族と社交",
    personal: "個人",
    influenceNetwork: "ネットワーク、影響力とライフスタイル",
    integratedServices: "統合サービス",
    members: "メンバー",
    concierge: "コンシェルジュ",
    metaverse: "メタバース",
    marketplace: "マーケットプレイス",
    backToDashboard: "ダッシュボードに戻る",
    quote: "卓越性、アイデンティティ、そして区別が私を定義します。",
    back: "戻る",
    export: "エクスポート",
    searchPlaceholder: "名前、役職、業界でフィルター...",
    connectionRequest: "接続リクエストを送信",
    pendingResponse: "⏳ 返信待ち",
    upgradeRequired: "アップグレードが必要",
    higherCircle: "このメンバーは上位サークルに属しています",
    contactRequirement: "連絡するには",
    sameLevelRequired: "メンバーシップは同じレベルである必要があります。",
    requiredLevel: "必要なレベル：",
    amount: "金額：",
    perMonth: "€/月",
    validate: "確認",
    refuse: "拒否",
    membersShown: "メンバー",
    membersShownPlural: "メンバー",
    displayed: "表示",
    displayedPlural: "表示",
    sendConnectionRequest: "接続リクエストを送信しますか",
    payment: "支払い",
    orderSummary: "注文概要",
    level: "レベル",
    monthlySubscription: "月額サブスクリプション",
    accessMembers: "あなたのレベルのメンバーへのアクセス",
    unlimitedConnections: "無制限の接続",
    exclusiveServices: "Aurora専用サービス",
    prioritySupport: "優先サポート",
    monthlyTotal: "月間合計",
    autoRenew: "毎月自動更新",
    paymentInfo: "支払い情報",
    cardNumber: "カード番号",
    expirationDate: "有効期限",
    nameOnCard: "カード名義",
    securePayment: "お支払い情報は安全に暗号化されています。銀行データは保存しません。",
    confirmPayment: "支払いを確認",
    conciergePage: "コンシェルジュ",
    metaversePage: "メタバース",
    marketplacePage: "マーケットプレイス",
    familyPage: "家族と社交",
    networkPage: "ネットワーク、影響力とライフスタイル",
    backToProfile: "プロフィールに戻る",
    // Security & Settings
    settings: "設定",
    securitySettings: "生体認証セキュリティ",
    biometricSecurity: "生体認証セキュリティ",
    manageAuthMethods: "認証方法を管理",
    detectedDevice: "検出されたデバイス",
    autoConfigDevice: "デバイスに基づく自動設定",
    webBiometricAuth: "ウェブ生体認証",
    registeredDevices: "登録済みデバイス",
    addAnotherDevice: "別のデバイスを追加",
    activateBiometric: "有効化",
    configuring: "設定中...",
    securityTips: "セキュリティのヒント",
    biometricFastSecure: "生体認証は高速で安全なログインを提供します",
    biometricDataLocal: "生体認証データはデバイスに保存されます",
    multipleDevices: "複数のデバイスを登録できます",
    passwordFallback: "パスワードログインは引き続き利用可能です",
    logout: "ログアウト",
    landingPages: "ランディングページ",
    administration: "管理",
    deleteAccount: "アカウントを削除",
    homeTagline: "成功、生活の芸術、そして平穏を融合させたい方のためのプライベートサークル。",
    homeDescription: "起業家、投資家、富裕層のための国際的な会員制クラブ。ビジネスチャンス、人脈、プレミアムコンシェルジュ、希少資産へのアクセスを提供します。",
    homePhilosophy: "「私たちは最高級へのシンプルなアプローチを信じています：露出を減らし、品質を高める。約束を減らし、結果を出す。騒音を減らし、本物の関係を築く。」",
  },
  ru: {
    welcome: "Добро пожаловать",
    description: "Разработанное для выдающихся членов мировой элиты, Aurora Society - это приложение, зарезервированное для самых влиятельных личностей.",
    continue: "Продолжить",
    selectLanguage: "Язык",
    register: "Зарегистрироваться",
    signIn: "Войти",
    allRightsReserved: "Все права защищены",
    termsAndConditions: "Условия использования",
    contact: "Контакт",
    email: "Электронная почта",
    invitationCode: "Код приглашения (обязательно)",
    login: "Войти",
    registration: "РЕГИСТРАЦИЯ",
    profilePhoto: "Фото Профиля",
    referralCode: "Реферальный Код",
    idCard: "Удостоверение Личности",
    scanId: "Сканировать Документ",
    firstName: "Имя",
    lastName: "Фамилия",
    honorificTitle: "Почетное Звание",
    mobileNumber: "Номер Мобильного",
    jobFunction: "Функция/Деятельность",
    activityDomain: "Область Деятельности",
    wealthLevel: "Уровень Состояния",
    personalQuote: "Личная Цитата (необязательно)",
    photoFormatsHint: "Рекомендуется: JPG, PNG или GIF",
    chooseFile: "Выбрать файл",
    jobFunctionPlaceholder: "CEO, Директор, Менеджер...",
    emailPlaceholder: "ваш@email.com",
    selectTitle: "Выберите ваше звание",
    selectActivityDomain: "Выберите вашу область",
    personalQuotePlaceholder: "Заполнить позже...",
    founderMember: "Член-Учредитель",
    associatedAccounts: "Связанные Аккаунты",
    acceptTermsPrefix: "Я принимаю",
    loading: "Загрузка...",
    exclusiveCircle: "Aurora Society - это эксклюзивный круг.",
    chosenMembers: "Каждый член выбран.",
    business: "БИЗНЕС",
    familySocial: "СЕМЬЯ И ОБЩЕСТВО",
    personal: "ЛИЧНОЕ",
    influenceNetwork: "СЕТИ, ВЛИЯНИЕ И СТИЛЬ ЖИЗНИ",
    integratedServices: "ИНТЕГРИРОВАННЫЕ УСЛУГИ",
    members: "ЧЛЕНЫ",
    concierge: "Консьерж",
    metaverse: "Метавселенная",
    marketplace: "Рынок",
    backToDashboard: "Вернуться к панели",
    quote: "Совершенство, идентичность и отличие определяют меня.",
    back: "Назад",
    export: "Экспорт",
    searchPlaceholder: "Фильтр по имени, должности, сектору...",
    connectionRequest: "Отправить запрос на подключение",
    pendingResponse: "⏳ Ожидание ответа",
    upgradeRequired: "Требуется обновление",
    higherCircle: "Этот член принадлежит к более высокому кругу",
    contactRequirement: "Чтобы связаться",
    sameLevelRequired: "ваше членство должно быть того же уровня.",
    requiredLevel: "Требуемый уровень:",
    amount: "Сумма:",
    perMonth: "€/месяц",
    validate: "Подтвердить",
    refuse: "Отказаться",
    membersShown: "член",
    membersShownPlural: "члены",
    displayed: "отображено",
    displayedPlural: "отображено",
    sendConnectionRequest: "Вы хотите отправить запрос на подключение",
    payment: "ОПЛАТА",
    orderSummary: "Сводка заказа",
    level: "Уровень",
    monthlySubscription: "Ежемесячная подписка",
    accessMembers: "Доступ к членам вашего уровня",
    unlimitedConnections: "Неограниченные подключения",
    exclusiveServices: "Эксклюзивные услуги Aurora",
    prioritySupport: "Приоритетная поддержка",
    monthlyTotal: "Итого за месяц",
    autoRenew: "Автоматически продлевается каждый месяц",
    paymentInfo: "Платежная информация",
    cardNumber: "Номер карты",
    expirationDate: "Срок действия",
    nameOnCard: "Имя на карте",
    securePayment: "Ваша платежная информация защищена и зашифрована. Мы не храним ваши банковские данные.",
    confirmPayment: "Подтвердить платеж",
    conciergePage: "Консьерж",
    metaversePage: "Метавселенная",
    marketplacePage: "Рынок",
    familyPage: "Семья и общество",
    networkPage: "Сети, влияние и стиль жизни",
    backToProfile: "Вернуться к профилю",
    // Security & Settings
    settings: "Настройки",
    securitySettings: "Биометрическая безопасность",
    biometricSecurity: "Биометрическая безопасность",
    manageAuthMethods: "Управление методами аутентификации",
    detectedDevice: "Обнаруженное устройство",
    autoConfigDevice: "Автоматическая настройка на основе вашего устройства",
    webBiometricAuth: "Веб-биометрическая аутентификация",
    registeredDevices: "Зарегистрированные устройства",
    addAnotherDevice: "Добавить другое устройство",
    activateBiometric: "Активировать",
    configuring: "Настройка...",
    securityTips: "Советы по безопасности",
    biometricFastSecure: "Биометрическая аутентификация обеспечивает быстрый и безопасный вход",
    biometricDataLocal: "Ваши биометрические данные остаются на вашем устройстве",
    multipleDevices: "Вы можете зарегистрировать несколько устройств",
    passwordFallback: "Вход по паролю остается доступным",
    logout: "Выйти",
    landingPages: "Целевые страницы",
    administration: "Администрирование",
    deleteAccount: "Удалить аккаунт",
    homeTagline: "Частный круг для тех, кто хочет совместить успех, искусство жизни и душевное спокойствие.",
    homeDescription: "Международный конфиденциальный клуб для предпринимателей, инвесторов и состоятельных семей, объединяющий деловые возможности, человеческую сеть, престижный консьерж-сервис и доступ к редким активам.",
    homePhilosophy: "«Мы верим в простой подход к высшему уровню: меньше публичности, больше качества. Меньше обещаний, больше результатов. Меньше шума, больше настоящих отношений.»",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('aurora-language');
    return (saved as Language) || 'fr';
  });

  useEffect(() => {
    localStorage.setItem('aurora-language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return (
      translations[language]?.[key] ??
      translations['fr']?.[key] ??
      translations['en']?.[key] ??
      key
    );
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const languages: { code: Language; name: string; flag: string }[] = [
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'pt', name: 'Português', flag: '🇵🇹' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
];
